//SAGA
export const ADD_TODO_SAGA = 'ADD_TODO_SAGA'
export const REMOVE_TODO_SAGA = 'REMOVE_TODO_SAGA'
export const CHECK_COMPLETED_TODO_SAGA = 'CHECK_COMPLETED_TODO_SAGA'
export const EDIT_TODO_SAGA = 'EDIT_TODO_SAGA'
export const CLEAR_COMPLETED_TODO_SAGA = 'CLEAR_COMPLETED_TODO_SAGA'


export const GET_LIST = 'GET_LIST'
export const ADD_TODO = 'ADD_TODO'
export const CHECK_COMPLETED_TODO = 'CHECK_COMPLETED_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const CLEAR_COMPLETED_TODO = 'CLEAR_COMPLETED_TODO'